server:server_new.c cJSON.c
	gcc -o inf-bonbon-server server_new.c -ldl cJSON.c -Wall -g
clean:
	rm inf-bonbon-server Child.in Child.out Grandson-1.in Grandson-2.in Grandson-3.in Grandson-1.out Grandson-2.out Grandson-3.out Fun-1.in Fun-2.in Fun-3.in
